name: Release

on:
  push:
    tags:
      - 'release-v*' # v로 시작하는 태그가 푸시될 때 실행

jobs:
  release:
    permissions:
      contents: write
    runs-on: macos-latest # macOS 환경에서 실행
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # 사용하는 pnpm 버전에 맞게 조절

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # 사용하는 Node.js 버전에 맞게 조절
          cache: 'pnpm'

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: ./apps/frontend # frontend 앱의 경로
          tagName: ${{ github.ref_name }}
          releaseName: 'App ${{ github.ref_name }}'
          releaseBody: 'See the assets to download this version.'
          releaseDraft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
